"""
Initial migration — creates all portfolio tables.
Generated by: python manage.py makemigrations
"""

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [

        # ── About ──────────────────────────────────────────
        migrations.CreateModel(
            name='About',
            fields=[
                ('id',               models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',             models.CharField(default='Mohtashim Usmani', max_length=120)),
                ('role_line',        models.CharField(default='Data Scientist · Full Stack Developer · Python Developer', max_length=200)),
                ('bio_paragraph_1',  models.TextField()),
                ('bio_paragraph_2',  models.TextField(blank=True)),
                ('bio_paragraph_3',  models.TextField(blank=True)),
                ('location',         models.CharField(default='Available Globally · Remote First', max_length=120)),
                ('email',            models.EmailField(default='mohtashim@email.com', max_length=254)),
                ('github_url',       models.URLField(blank=True)),
                ('linkedin_url',     models.URLField(blank=True)),
                ('twitter_url',      models.URLField(blank=True)),
                ('is_available',     models.BooleanField(default=True)),
                ('profile_image',    models.ImageField(blank=True, null=True, upload_to='about/')),
                ('resume_file',      models.FileField(blank=True, null=True, upload_to='resume/')),
                ('updated_at',       models.DateTimeField(auto_now=True)),
            ],
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),

        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id',    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.about')),
                ('value', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={'ordering': ['order'], 'verbose_name': 'Stat Card', 'verbose_name_plural': 'Stat Cards'},
        ),

        # ── Skill ─────────────────────────────────────────
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id',          models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',        models.CharField(max_length=80)),
                ('category',    models.CharField(
                    choices=[
                        ('language','Language'), ('framework','Framework'), ('frontend','Frontend'),
                        ('database','Database'), ('ai_ml','AI / ML'), ('data','Data'),
                        ('analytics','Analytics'), ('backend','Backend'), ('devops','DevOps'), ('other','Other'),
                    ],
                    default='other', max_length=30
                )),
                ('level',       models.PositiveSmallIntegerField(
                    default=80,
                    validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]
                )),
                ('icon_name',   models.CharField(blank=True, max_length=80)),
                ('color',       models.CharField(default='#FF1744', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active',   models.BooleanField(default=True)),
                ('order',       models.PositiveSmallIntegerField(default=0)),
            ],
            options={'ordering': ['order', 'name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),

        # ── Project ───────────────────────────────────────
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id',          models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number',      models.CharField(max_length=4)),
                ('title',       models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('badge',       models.CharField(
                    choices=[
                        ('Machine Learning','Machine Learning'), ('Full Stack','Full Stack'),
                        ('Web App','Web App'), ('Analytics','Analytics'),
                        ('Data Science','Data Science'), ('API','API'), ('Mobile','Mobile'), ('Other','Other'),
                    ],
                    default='Web App', max_length=40
                )),
                ('accent',      models.CharField(default='#FF1744', max_length=20)),
                ('tech_stack',  models.JSONField(default=list)),
                ('github_url',  models.URLField(blank=True)),
                ('live_url',    models.URLField(blank=True)),
                ('thumbnail',   models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('is_featured', models.BooleanField(default=True)),
                ('is_active',   models.BooleanField(default=True)),
                ('order',       models.PositiveSmallIntegerField(default=0)),
                ('created_at',  models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),

        # ── Experience ────────────────────────────────────
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id',           models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year',         models.CharField(max_length=10)),
                ('title',        models.CharField(max_length=120)),
                ('organization', models.CharField(max_length=120)),
                ('description',  models.TextField()),
                ('tags',         models.JSONField(default=list)),
                ('icon_name',    models.CharField(blank=True, max_length=80)),
                ('side',         models.CharField(choices=[('left','Left'),('right','Right')], default='left', max_length=5)),
                ('order',        models.PositiveSmallIntegerField(default=0)),
                ('is_active',    models.BooleanField(default=True)),
            ],
            options={'ordering': ['order'], 'verbose_name': 'Experience', 'verbose_name_plural': 'Experience Timeline'},
        ),

        # ── ContactMessage ────────────────────────────────
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id',         models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',       models.CharField(max_length=120)),
                ('email',      models.EmailField(max_length=254)),
                ('subject',    models.CharField(max_length=200)),
                ('message',    models.TextField()),
                ('is_read',    models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),

        # ── SocialLink ────────────────────────────────────
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id',        models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform',  models.CharField(
                    choices=[
                        ('github','GitHub'), ('linkedin','LinkedIn'), ('twitter','Twitter / X'),
                        ('email','Email'), ('kaggle','Kaggle'), ('medium','Medium'), ('other','Other'),
                    ],
                    max_length=30
                )),
                ('label',     models.CharField(max_length=60)),
                ('url',       models.CharField(max_length=200)),
                ('handle',    models.CharField(blank=True, max_length=120)),
                ('icon_name', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('order',     models.PositiveSmallIntegerField(default=0)),
            ],
            options={'ordering': ['order'], 'verbose_name': 'Social Link', 'verbose_name_plural': 'Social Links'},
        ),
    ]