# Generated by Django 4.2.30 on 2026-05-22 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_update_project_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='code_tags',
            field=models.JSONField(blank=True, default=list, help_text='Hero orbit tags as a JSON array, e.g. ["django runserver", "npm run build"]'),
        ),
        migrations.AlterField(
            model_name='about',
            name='bio_paragraph_1',
            field=models.TextField(help_text='First bio paragraph in the About section'),
        ),
        migrations.AlterField(
            model_name='about',
            name='bio_paragraph_2',
            field=models.TextField(blank=True, help_text='Second bio paragraph (optional)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='bio_paragraph_3',
            field=models.TextField(blank=True, help_text='Third bio paragraph (optional)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='is_available',
            field=models.BooleanField(default=True, help_text="Toggles the 'Available for hire' badge on the hero section"),
        ),
        migrations.AlterField(
            model_name='about',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile / avatar photo', null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Downloadable CV / resume', null=True, upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='role_line',
            field=models.CharField(default='Data Scientist · Full Stack Developer · Python Developer', help_text='Shown under the name (e.g. in footer / hero sub-text)', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='label',
            field=models.CharField(help_text="e.g. 'Years Experience'", max_length=60),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='value',
            field=models.CharField(help_text="e.g. '3+', '15+'", max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Automatically captured on submission', null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text="Mark as read once you've seen it"),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_replied',
            field=models.BooleanField(default=False, help_text='Mark as replied after you respond'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='icon_name',
            field=models.CharField(blank=True, help_text='react-icons identifier, e.g. FaCode, FaBrain', max_length=80),
        ),
        migrations.AlterField(
            model_name='experience',
            name='organization',
            field=models.CharField(help_text="e.g. 'Self-Taught', 'Freelance'", max_length=120),
        ),
        migrations.AlterField(
            model_name='experience',
            name='side',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', help_text='Which side of the timeline the card appears on', max_length=5),
        ),
        migrations.AlterField(
            model_name='experience',
            name='tags',
            field=models.JSONField(default=list, help_text='Tech/skill tags, e.g. ["Python","Django"]'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='year',
            field=models.CharField(help_text="e.g. '2022' or '2022–2023'", max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='accent',
            field=models.CharField(default='#FF1744', help_text='Card accent colour (hex)', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='2–3 sentence project description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='Live demo URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.CharField(help_text="Display number on card, e.g. '01', '02'", max_length=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(default=list, help_text='JSON array of tech tags, e.g. ["Python","Django","React"]'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='color',
            field=models.CharField(default='#FF1744', help_text='Hex color for the icon glow, e.g. #3776AB', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, help_text='One-line description shown on the card', max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_name',
            field=models.CharField(blank=True, help_text='react-icons identifier, e.g. FaPython, SiDjango', max_length=80),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveSmallIntegerField(default=80, help_text='Proficiency 0–100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='handle',
            field=models.CharField(blank=True, help_text="Username / handle shown in the UI, e.g. '@mohtashim_dev'", max_length=120),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_name',
            field=models.CharField(blank=True, help_text='react-icons identifier', max_length=80),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='label',
            field=models.CharField(help_text="Display label, e.g. 'GitHub'", max_length=60),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.CharField(help_text="Full URL or 'mailto:' link", max_length=200),
        ),
    ]
